# Generated by Django 2.1.7 on 2019-03-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('p', 'Pendente'), ('c', 'Concluído')], max_length=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(null=True)),
                ('excluido_em', models.DateField(null=True)),
            ],
        ),
    ]
