# Generated by Django 2.1.7 on 2019-03-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0002_auto_20190316_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='description',
            new_name='descricao',
        ),
    ]
