# Generated by Django 2.1.7 on 2019-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0003_auto_20190316_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
