# Generated by Django 2.1.7 on 2019-03-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklists', '0004_tasks_excluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='excluido_em',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
